language: python
python:
  - "3.5"

cache:
  directories:
    - $HOME/.pip-cache/
    
# ignore the virtualenv that Travis creates
# setup a secure login to CodeCov
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - secure: 2c0250fb-dfb1-45c9-abaf-cd3d874326c5
# install mdl for checking Markdown
before_install:
  - gem install mdl
notifications:
  email: never

install:
  - pip install --upgrade pip
  - python3 -m pip install -r requirements.txt
  - pip3 install pytest-flake8
  - pip3 install pytest-cov
  - pip3 install autopep8
  - pip3 install gspread oauth2client
  - pip install --upgrade pipenv
  - pipenv install --dev --three
  
script:
  - pipenv run pytest --cov-config pytest.cov --cov
  - pytest tests
  - mdl README.md
  - coverage run --source tests -m py.test 
  - coverage report 

after_success:
  pipenv run codecov

